name: CI
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Node
        uses: actions/setup-node@v1
      - name: Yarn Install
        run: yarn install
      - name: Prettier
        run: yarn prettier:check
      - name: Lint
        run: yarn lint || echo "Disable linter for now to enable Yarn V2"
      - name: Build
        run: yarn build
