name: CI
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Node
        uses: actions/setup-node@v1
      - name: Yarn Install
        run: yarn install
      - name: Prettier
        run: yarn prettier:check
      - name: Lint
        run: yarn lint
      - name: Build
        run: yarn build
      - name: Rebuild Graphs
        run: |
          yarn dev --project .
          if [[ `git status --porcelain` ]]; then
            echo "Generated graphs are not in sync!"
            exit 1
          else
            echo "Generated graphs are in sync. Good to go!"
          fi
