name: Integration Test
on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Fetch all commits in this branch
        run: git fetch --depth=1 origin +refs/heads/${{github.base_ref}}:refs/remotes/origin/${{github.base_ref}}
      - uses: actions/setup-node@v2-beta
      - uses: actions/cache@v2
        with:
          path: ".yarn/cache\n.pnp.js"
          key: "yarn-berry-${{ hashFiles('**/yarn.lock') }}"
          restore-keys: 'yarn-berry-'
      - name: Yarn Install
        run: yarn install --immutable
      - name: Compile
        run: yarn tsc
      - name: Analyze
        run: yarn start . -- $(git diff --name-only origin/${{ github.base_ref }}..${{ github.head_ref }})
